print("Welcome to the Band Name Generator")
city=input("Which city did you grew up in?\n")
print(city)
pet=input("What is the name of your pet?\n")
print(pet)
print("Your Band name could be :"+city+" "+pet)